//Essa classe abstrada é o servidor baseado em fluxo de dados, fornecendo as funcionalidades básicas do CORBA para o servidor. A classe servidora CalculadoraImpl estende CalculadoraPOA.
package CalculadoraApp;


/**
* CalculadoraApp/CalculadoraPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Calculadora.idl
* Quarta-feira, 4 de Novembro de 2020 13h51min37s GMT-03:00
*/

public abstract class CalculadoraPOA extends org.omg.PortableServer.Servant
 implements CalculadoraApp.CalculadoraOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("adicao", new java.lang.Integer (0));
    _methods.put ("subtracao", new java.lang.Integer (1));
    _methods.put ("multiplicacao", new java.lang.Integer (2));
    _methods.put ("divisao", new java.lang.Integer (3));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // CalculadoraApp/Calculadora/adicao
       {
         int x = in.read_long ();
         int y = in.read_long ();
         int $result = (int)0;
         $result = this.adicao (x, y);
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 1:  // CalculadoraApp/Calculadora/subtracao
       {
         int x = in.read_long ();
         int y = in.read_long ();
         int $result = (int)0;
         $result = this.subtracao (x, y);
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 2:  // CalculadoraApp/Calculadora/multiplicacao
       {
         int x = in.read_long ();
         int y = in.read_long ();
         int $result = (int)0;
         $result = this.multiplicacao (x, y);
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 3:  // CalculadoraApp/Calculadora/divisao
       {
         int x = in.read_long ();
         int y = in.read_long ();
         double $result = (double)0;
         $result = this.divisao (x, y);
         out = $rh.createReply();
         out.write_double ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:CalculadoraApp/Calculadora:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Calculadora _this() 
  {
    return CalculadoraHelper.narrow(
    super._this_object());
  }

  public Calculadora _this(org.omg.CORBA.ORB orb) 
  {
    return CalculadoraHelper.narrow(
    super._this_object(orb));
  }


} // class CalculadoraPOA
