//Essa interface contém os métodos definidos na IDL, atráves do mapeamento IDL-to-Java. Essa interface é compartilhada por stubs e skeletons.

package CalculadoraApp;


/**
* CalculadoraApp/CalculadoraOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Calculadora.idl
* Quarta-feira, 4 de Novembro de 2020 13h51min37s GMT-03:00
*/

public interface CalculadoraOperations 
{
  int adicao (int x, int y);
  int subtracao (int x, int y);
  int multiplicacao (int x, int y);
  double divisao (int x, int y);
} // interface CalculadoraOperations
