//Essa interface contém a versão java da nossa interface IDL. A interface Calculadora.java estende org.omg.CORBA.Object fornecendo as funcionalidades padrões dos objetos CORBA. Assim como CalculadoraPOA ela também estende a interface CalculadoraOperations.
package CalculadoraApp;

/**
* CalculadoraApp/Calculadora.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Calculadora.idl
* Quarta-feira, 4 de Novembro de 2020 13h51min37s GMT-03:00
*/

public interface Calculadora extends CalculadoraOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Calculadora





